In [ ]:
from google_drive_downloader import GoogleDriveDownloader as gdd

gdd.download_file_from_google_drive(file_id='1SQ46vbMP1XMrsGgKRlsFzstPhMovIiVD',
                                    dest_path='./data/raw/TomsHardware.data')

gdd.download_file_from_google_drive(file_id='1uaY3neZ4kH11oMBQXXDaYrryDNhnlfDP',
                                    dest_path='./data/raw/Twitter.data')

## Twitter Data

Preprocessing of the data

In [54]:
import pandas as pd
import re
import numpy as np

In [55]:
dataframe = []
with open('data/raw/Twitter.data') as myfile:
    for i in myfile:
        dataframe.append(i)

In [56]:
dataframe2 = []
for i in range(len(dataframe)):
    dataframe2.append(re.findall('[0-9.0-9]+',dataframe[i]))

In [57]:
dataframe3 = np.array(dataframe2).reshape(len(dataframe2), len(dataframe2[0]))

In [58]:
df = pd.DataFrame(dataframe3)

In [59]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,68,69,70,71,72,73,74,75,76,77
0,0,2,0,0,1,1,1,0,1,0,...,1.000000,1.000000,0,2,0,0,1,1,1,0.0
1,2,1,0,0,0,0,4,2,1,0,...,0.000000,1.000000,2,1,0,0,0,0,4,0.5
2,1,0,0,0,0,4,1,1,0,0,...,1.000000,1.000000,1,0,0,0,0,4,1,0.0
3,1,0,0,1,0,0,1,1,0,0,...,0.000000,1.000000,1,0,0,1,0,0,1,2.5
4,0,1,0,0,1,2,3,0,1,0,...,1.000000,1.000000,0,1,0,0,1,2,3,0.5

Maintentant on récupère le nom des colonnes

In [60]:
Columns = ['NCD_0', 'NCD_1', 'NCD_2', 'NCD_3', 'NCD_4', 'NCD_5', 'NCD_6',
            'AI_0', 'AI_1', 'AI_2', 'AI_3', 'AI_4', 'AI_5', 'AI_6',
          'AS(NA)_0', 'AS(NA)_1', 'AS(NA)_2', 'AS(NA)_3', 'AS(NA)_4',
          'AS(NA)_5', 'AS(NA)_6', 'BL_0', 'BL_1', 'BL_2', 'BL_3', 
           'BL_4', 'BL_5', 'BL_6', 'NAC_0', 'NAC_1', 'NAC_2', 'NAC_3', 
           'NAC_4', 'NAC_5', 'NAC_6', 'AS(NAC)_0', 'AS(NAC)_1', 'AS(NAC)_2', 'AS(NAC)_3', 'AS(NAC)_4',
          'AS(NAC)_5', 'AS(NAC)_6', 'CS_0', 'CS_1', 'CS_2', 'CS_3', 'CS_4', 'CS_5', 'CS_6',
          'AT_0', 'AT_1', 'AT_2', 'AT_3', 'AT_4', 'AT_5', 'AT_6', 'NA_0', 'NA_1', 'NA_2',
           'NA_3', 'NA_4', 'NA_5', 'NA_6', 'ADL_0', 'ADL_1', 'ADL_2', 'ADL_3', 'ADL_4', 'ADL_5', 'ADL_6',
          'NAD_0', 'NAD_1', 'NAD_2', 'NAD_3', 'NAD_4', 'NAD_5', 'NAD_6', 'Value']

In [61]:
df1 = pd.DataFrame(dataframe3, columns=Columns)

In [62]:
df1 = df1.astype(float)

In [63]:
df1.head()

,NCD_0,NCD_1,NCD_2,NCD_3,NCD_4,NCD_5,NCD_6,AI_0,AI_1,AI_2,...,ADL_5,ADL_6,NAD_0,NAD_1,NAD_2,NAD_3,NAD_4,NAD_5,NAD_6,Value
0,0.0,2.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,...,1.0,1.0,0.0,2.0,0.0,0.0,1.0,1.0,1.0,0.0
1,2.0,1.0,0.0,0.0,0.0,0.0,4.0,2.0,1.0,0.0,...,0.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,4.0,0.5
2,1.0,0.0,0.0,0.0,0.0,4.0,1.0,1.0,0.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,4.0,1.0,0.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,2.5
4,0.0,1.0,0.0,0.0,1.0,2.0,3.0,0.0,1.0,0.0,...,1.0,1.0,0.0,1.0,0.0,0.0,1.0,2.0,3.0,0.5

In [64]:
df1.to_csv('data/TwitterRegression.csv')

## TomsHardware Data

In [65]:
dataframe = []
with open('data/raw/TomsHardware.data') as myfile:
    for i in myfile:
        dataframe.append(i)

In [66]:
dataframe2 = []
for i in range(len(dataframe)):
    dataframe2.append(re.findall('[0-9.0-9]+',dataframe[i]))

In [67]:
dataframe2 = []
for i in range(len(dataframe)):
    dataframe2.append(re.findall('[0-9.0-9]+',dataframe[i]))

In [68]:
dataframe3 = np.array(dataframe2).reshape(len(dataframe2), len(dataframe2[0]))

In [69]:
df = pd.DataFrame(dataframe3)

In [70]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,87,88,89,90,91,92,93,94,95,96
0,0,0,0,0,0,0,0,0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.5
1,0,0,0,0,0,0,0,0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.5
2,0,0,0,0,0,0,0,0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.0
3,0,0,0,0,0,0,0,0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.0
4,0,0,0,0,0,0,0,0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.5

In [71]:
Columns = ['NCD_0', 'NCD_1', 'NCD_2', 'NCD_3', 'NCD_4', 'NCD_5', 'NCD_6', 'NCD_7',
           'BL_0', 'BL_1', 'BL_2', 'BL_3', 'BL_4', 'BL_5', 'BL_6', 'BL_7',
           'NAD_0', 'NAD_1', 'NAD_2', 'NAD_3', 'NAD_4', 'NAD_5', 'NAD_6', 'NAD_7',
            'AI_0', 'AI_1', 'AI_2', 'AI_3', 'AI_4', 'AI_5', 'AI_6', 'AI_7',
            'NAC_0', 'NAC_1', 'NAC_2', 'NAC_3', 'NAC_4', 'NAC_5', 'NAC_6', 'NAC_7',
           'ND_0', 'ND_1', 'ND_2', 'ND_3', 'ND_4', 'ND_5', 'ND_6', 'ND_7',
           'CS_0', 'CS_1', 'CS_2', 'CS_3', 'CS_4', 'CS_5', 'CS_6', 'CS_7',
           'AT_0', 'AT_1', 'AT_2', 'AT_3', 'AT_4', 'AT_5', 'AT_6', 'AT_7',
           'NA_0', 'NA_1', 'NA_2', 'NA_3', 'NA_4', 'NA_5', 'NA_6', 'NA_7',
           'ADL_0', 'ADL_1', 'ADL_2', 'ADL_3', 'ADL_4', 'ADL_5', 'ADL_6', 'ADL_7',
           'AS(NA)_0', 'AS(NA)_1', 'AS(NA)_2', 'AS(NA)_3', 'AS(NA)_4',
          'AS(NA)_5', 'AS(NA)_6', 'AS(NA)_7', 'AS(NAC)_0', 'AS(NAC)_1', 'AS(NAC)_2', 'AS(NAC)_3', 'AS(NAC)_4',
          'AS(NAC)_5', 'AS(NAC)_6', 'AS(NAC)_7', 'Value']

In [72]:
df1 = pd.DataFrame(dataframe3, columns=Columns)

In [73]:
df1 = df1.astype(float)

In [74]:
df1.head()

,NCD_0,NCD_1,NCD_2,NCD_3,NCD_4,NCD_5,NCD_6,NCD_7,BL_0,BL_1,...,AS(NA)_7,AS(NAC)_0,AS(NAC)_1,AS(NAC)_2,AS(NAC)_3,AS(NAC)_4,AS(NAC)_5,AS(NAC)_6,AS(NAC)_7,Value
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.5
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.5

In [75]:
df1.to_csv('data/TomsHardwareRegression.csv')

In [76]:
import pandas as pd
twitter_reg = pd.read_csv('data/TwitterRegression.csv').drop(columns = 'Unnamed: 0')
toms_reg = pd.read_csv('data/TomsHardwareRegression.csv').drop(columns = 'Unnamed: 0')

In [77]:
twitter_reg

,NCD_0,NCD_1,NCD_2,NCD_3,NCD_4,NCD_5,NCD_6,AI_0,AI_1,AI_2,...,ADL_5,ADL_6,NAD_0,NAD_1,NAD_2,NAD_3,NAD_4,NAD_5,NAD_6,Value
0,0.0,2.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,...,1.000000,1.000000,0.0,2.0,0.0,0.0,1.0,1.0,1.0,0.0
1,2.0,1.0,0.0,0.0,0.0,0.0,4.0,2.0,1.0,0.0,...,0.000000,1.000000,2.0,1.0,0.0,0.0,0.0,0.0,4.0,0.5
2,1.0,0.0,0.0,0.0,0.0,4.0,1.0,1.0,0.0,0.0,...,1.000000,1.000000,1.0,0.0,0.0,0.0,0.0,4.0,1.0,0.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.000000,1.000000,1.0,0.0,0.0,1.0,0.0,0.0,1.0,2.5
4,0.0,1.0,0.0,0.0,1.0,2.0,3.0,0.0,1.0,0.0,...,1.000000,1.000000,0.0,1.0,0.0,0.0,1.0,2.0,3.0,0.5
5,1.0,0.0,0.0,1.0,2.0,3.0,0.0,1.0,0.0,0.0,...,1.000000,0.000000,1.0,0.0,0.0,1.0,2.0,3.0,0.0,1.0
6,1.0,0.0,0.0,0.0,2.0,0.0,2.0,1.0,0.0,0.0,...,0.000000,1.000000,1.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0
7,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,0.0,...,1.000000,1.000000,0.0,2.0,0.0,0.0,0.0,1.0,1.0,2.0
8,2.0,0.0,0.0,0.0,1.0,1.0,2.0,2.0,0.0,0.0,...,1.000000,1.000000,2.0,0.0,0.0,0.0,1.0,1.0,2.0,1.0
9,0.0,1.0,1.0,2.0,2.0,0.0,3.0,0.0,1.0,1.0,...,0.000000,1.000000,0.0,1.0,1.0,2.0,2.0,0.0,3.0,0.5
10,1.0,1.0,2.0,2.0,0.0,3.0,1.0,1.0,1.0,2.0,...,1.000000,1.000000,1.0,1.0,2.0,2.0,0.0,3.0,1.0,0.5
11,0.0,1.0,1.0,1.0,2.0,2.0,0.0,0.0,1.0,1.0,...,1.000000,0.000000,0.0,1.0,1.0,1.0,2.0,2.0,0.0,0.0
12,0.0,1.0,1.0,0.0,0.0,0.0,12.0,0.0,1.0,1.0,...,0.000000,1.000000,0.0,1.0,1.0,0.0,0.0,0.0,12.0,17.5
13,1.0,1.0,0.0,0.0,0.0,12.0,34.0,1.0,1.0,0.0,...,1.000000,1.000000,1.0,1.0,0.0,0.0,0.0,12.0,34.0,0.5
14,1.0,0.0,0.0,0.0,12.0,34.0,1.0,1.0,0.0,0.0,...,1.000000,1.000000,1.0,0.0,0.0,0.0,12.0,34.0,1.0,6.5
15,1.0,0.0,13.0,4.0,11.0,9.0,10.0,0.0,0.0,1.0,...,1.000000,1.000000,1.0,0.0,13.0,4.0,11.0,9.0,10.0,28.5
16,0.0,13.0,4.0,11.0,9.0,10.0,18.0,0.0,1.0,2.0,...,1.000000,1.000000,0.0,13.0,4.0,11.0,9.0,10.0,18.0,23.5
17,13.0,4.0,11.0,9.0,10.0,18.0,39.0,1.0,2.0,1.0,...,1.000000,1.000000,13.0,4.0,11.0,9.0,10.0,18.0,39.0,12.0
18,4.0,11.0,9.0,10.0,18.0,39.0,8.0,2.0,1.0,5.0,...,1.000000,1.000000,4.0,11.0,9.0,10.0,18.0,39.0,8.0,8.0
19,11.0,9.0,10.0,18.0,39.0,8.0,16.0,1.0,5.0,7.0,...,1.000000,1.000000,11.0,9.0,10.0,18.0,39.0,8.0,16.0,1.0
20,9.0,10.0,18.0,39.0,8.0,16.0,0.0,5.0,7.0,4.0,...,1.000000,0.000000,9.0,10.0,18.0,39.0,8.0,16.0,0.0,6.0
21,1.0,0.0,1.0,6.0,0.0,0.0,2.0,1.0,0.0,1.0,...,0.000000,1.000000,1.0,0.0,1.0,6.0,0.0,0.0,2.0,1.0
22,0.0,1.0,6.0,0.0,0.0,2.0,2.0,0.0,1.0,3.0,...,1.000000,1.000000,0.0,1.0,6.0,0.0,0.0,2.0,2.0,0.0
23,0.0,2.0,2.0,0.0,0.0,8.0,4.0,0.0,2.0,2.0,...,2.125000,4.750000,0.0,2.0,2.0,0.0,0.0,8.0,4.0,1.5
24,2.0,2.0,0.0,0.0,8.0,4.0,1.0,2.0,2.0,0.0,...,4.750000,3.000000,2.0,2.0,0.0,0.0,8.0,4.0,1.0,2.0
25,2.0,0.0,0.0,8.0,4.0,1.0,1.0,2.0,0.0,0.0,...,3.000000,3.000000,2.0,0.0,0.0,8.0,4.0,1.0,2.0,1.5
26,1.0,0.0,0.0,0.0,0.0,8.0,0.0,1.0,0.0,0.0,...,1.000000,0.000000,2.0,1.0,1.0,0.0,1.0,8.0,0.0,1.5
27,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,1.0,1.0,0.0,1.0,8.0,0.0,0.0,5.0
28,0.0,0.0,0.0,8.0,0.0,0.0,3.0,0.0,0.0,1.0,...,0.000000,1.666667,1.0,0.0,1.0,8.0,0.0,0.0,3.0,4.5
29,0.0,0.0,8.0,0.0,0.0,3.0,7.0,0.0,1.0,8.0,...,1.666667,2.428571,0.0,1.0,8.0,0.0,0.0,3.0,7.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583220,8.0,8.0,27.0,17.0,11.0,9.0,12.0,4.0,6.0,11.0,...,1.555556,1.384615,8.0,8.0,27.0,17.0,11.0,9.0,13.0,19.5
583221,27.0,17.0,11.0,9.0,12.0,17.0,21.0,11.0,5.0,6.0,...,1.277778,1.380952,27.0,17.0,11.0,9.0,13.0,18.0,21.0,18.0
583222,17.0,11.0,9.0,12.0,17.0,21.0,14.0,5.0,6.0,5.0,...,1.380952,1.000000,17.0,11.0,9.0,13.0,18.0,21.0,14.0,17.5
583223,11.0,9.0,12.0,17.0,21.0,14.0,22.0,6.0,5.0,7.0,...,1.000000,1.090909,11.0,9.0,13.0,18.0,21.0,14.0,22.0,12.0
583224,9.0,12.0,17.0,21.0,14.0,22.0,13.0,5.0,7.0,10.0,...,1.090909,1.538462,9.0,13.0,18.0,21.0,14.0,22.0,13.0,11.0
583225,435.0,349.0,386.0,317.0,325.0,441.0,511.0,231.0,173.0,182.0,...,1.000000,1.000000,435.0,349.0,386.0,317.0,325.0,441.0,511.0,418.0
583226,349.0,386.0,317.0,325.0,441.0,511.0,417.0,173.0,182.0,173.0,...,1.000000,1.000000,349.0,386.0,317.0,325.0,441.0,511.0,417.0,583.0
583227,317.0,325.0,441.0,511.0,417.0,419.0,747.0,173.0,117.0,217.0,...,1.000000,1.000000,317.0,325.0,441.0,511.0,417.0,419.0,747.0,346.0
583228,325.0,441.0,511.0,417.0,419.0,747.0,363.0,117.0,217.0,261.0,...,1.000000,1.000000,325.0,441.0,511.0,417.0,419.0,747.0,363.0,371.5
583229,363.0,329.0,414.0,514.0,533.0,486.0,417.0,168.0,167.0,196.0,...,1.000000,1.000000,363.0,329.0,414.0,514.0,533.0,486.0,417.0,326.0
583230,486.0,417.0,339.0,313.0,356.0,379.0,1409.0,256.0,198.0,182.0,...,1.000000,1.000000,486.0,417.0,339.0,313.0,356.0,379.0,1409.0,1422.5
583231,417.0,339.0,313.0,356.0,379.0,1409.0,1379.0,198.0,182.0,170.0,...,1.000000,1.002175,417.0,339.0,313.0,356.0,379.0,1409.0,1379.0,1382.5
583232,339.0,313.0,356.0,379.0,1409.0,1379.0,1466.0,182.0,170.0,196.0,...,1.002175,1.000000,339.0,313.0,356.0,379.0,1409.0,1379.0,1466.0,1307.5
583233,313.0,356.0,379.0,1409.0,1379.0,1466.0,1299.0,170.0,196.0,183.0,...,1.000000,1.000000,313.0,356.0,379.0,1409.0,1379.0,1466.0,1299.0,1344.5
583234,356.0,379.0,1409.0,1379.0,1466.0,1299.0,1316.0,196.0,183.0,705.0,...,1.000000,1.000000,356.0,379.0,1409.0,1379.0,1466.0,1299.0,1316.0,1467.5
583235,379.0,1409.0,1379.0,1466.0,1299.0,1316.0,1373.0,183.0,705.0,711.0,...,1.000000,1.000000,379.0,1409.0,1379.0,1466.0,1299.0,1316.0,1373.0,1431.0
583236,1300.0,1526.0,1311.0,1183.0,1445.0,1454.0,2047.0,639.0,658.0,544.0,...,1.000000,1.000000,1300.0,1526.0,1311.0,1183.0,1445.0,1454.0,2047.0,1380.5
583237,1526.0,1311.0,1183.0,1445.0,1454.0,2047.0,1437.0,658.0,544.0,549.0,...,1.000000,1.000000,1526.0,1311.0,1183.0,1445.0,1454.0,2047.0,1437.0,1300.5
583238,1700.0,1386.0,1364.0,1437.0,1627.0,2040.0,1736.0,697.0,579.0,501.0,...,1.000490,1.000000,1700.0,1386.0,1364.0,1437.0,1627.0,2040.0,1736.0,1625.0
583239,1280.0,1725.0,758.0,66.0,1254.0,1146.0,1353.0,493.0,527.0,293.0,...,1.211255,1.197940,1287.0,1735.0,759.0,67.0,1257.0,1155.0,1359.0,1276.5
583240,1725.0,758.0,66.0,1254.0,1146.0,1353.0,1298.0,527.0,293.0,19.0,...,1.197940,1.249045,1735.0,759.0,67.0,1257.0,1155.0,1359.0,1309.0,1311.0
583241,758.0,66.0,1254.0,1146.0,1353.0,1298.0,1240.0,293.0,19.0,487.0,...,1.249045,1.136656,759.0,67.0,1257.0,1155.0,1359.0,1309.0,1244.0,1299.0
583242,66.0,1254.0,1146.0,1353.0,1298.0,1240.0,1364.0,19.0,487.0,401.0,...,1.136656,1.161829,67.0,1257.0,1155.0,1359.0,1309.0,1244.0,1378.0,1215.0
583243,1473.0,1518.0,1289.0,1228.0,1343.0,1999.0,1789.0,527.0,582.0,582.0,...,1.147557,1.155259,1483.0,1527.0,1300.0,1240.0,1352.0,2006.0,1797.0,1641.0
583244,1518.0,1289.0,1228.0,1343.0,1999.0,1789.0,1643.0,582.0,582.0,487.0,...,1.155259,1.143549,1527.0,1300.0,1240.0,1352.0,2006.0,1797.0,1651.0,2107.5
583245,1289.0,1228.0,1343.0,1999.0,1789.0,1643.0,1626.0,582.0,487.0,506.0,...,1.143549,1.185776,1300.0,1240.0,1352.0,2006.0,1797.0,1651.0,1631.0,2120.0
583246,1228.0,1343.0,1999.0,1789.0,1643.0,1626.0,2582.0,487.0,506.0,752.0,...,1.185776,1.217879,1240.0,1352.0,2006.0,1797.0,1651.0,1631.0,2584.0,1490.0
583247,1343.0,1999.0,1789.0,1643.0,1626.0,2582.0,1649.0,506.0,752.0,663.0,...,1.217879,1.230072,1352.0,2006.0,1797.0,1651.0,1631.0,2584.0,1656.0,1407.5
583248,1689.0,1468.0,0.0,1721.0,1699.0,1565.0,1688.0,618.0,610.0,0.0,...,1.129936,1.100945,1702.0,1478.0,0.0,1722.0,1702.0,1570.0,1694.0,1465.5
583249,1468.0,0.0,1721.0,1699.0,1565.0,1688.0,1453.0,610.0,0.0,681.0,...,1.100945,1.185185,1478.0,0.0,1722.0,1702.0,1570.0,1694.0,1458.0,1606.0

In [78]:
toms_reg = toms_reg.drop(columns=['NCD_7', 'BL_7', 'NAD_7', 'AI_7', 'NAC_7', 'ND_7', 'CS_7', 'AT_7', 'NA_7', 'ADL_7', 'AS(NA)_7', 'AS(NAC)_7'])

On enlève BL qui est du crossfeature

In [79]:
twitter_reg = twitter_reg.drop(columns=['BL_0', 'BL_1', 'BL_2', 'BL_3', 'BL_4', 'BL_5', 'BL_6'])
toms_reg = toms_reg.drop(columns=['BL_0', 'BL_1', 'BL_2', 'BL_3', 'BL_4', 'BL_5', 'BL_6'])

On enlève les features non dans l'intersection des deux tables

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
toms_reg = toms_reg.drop(columns = ['ND_0', 'ND_1', 'ND_2', 'ND_3',
   'ND_4', 'ND_5', 'ND_6'])

In [4]:
twitter_reg['site'] = 'Twitter'
toms_reg['site'] = 'Tomshardware'

In [5]:
twitter_reg = twitter_reg.reindex(sorted(twitter_reg.columns), axis=1)
toms_reg = toms_reg.reindex(sorted(toms_reg.columns), axis=1)

In [6]:
twitter_reg = pd.concat([twitter_reg.iloc[:, -1], twitter_reg.iloc[:, :-1]], axis=1, sort=False)
toms_reg = pd.concat([toms_reg.iloc[:, -1], toms_reg.iloc[:, :-1]], axis=1, sort=False)

In [7]:
final = pd.concat([twitter_reg, toms_reg])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    final.iloc[:, :-1], final.iloc[:, -1], test_size=0.15)

In [17]:
X_train.to_csv('data/data_train.csv', index = False)
y_train = pd.Series(y_train)
y_train.to_csv('data/labels_train.csv', index = False, header = True)
X_test.to_csv('data/data_test.csv', index = False)
y_test = pd.Series(y_test)
y_test.to_csv('data/labels_test.csv', index = False, header = True)